#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# dev コンテナが起動中なら中で実行、ダメならホストで実行
if command -v docker >/dev/null 2>&1 && docker compose ps >/dev/null 2>&1; then
  docker compose exec -T app yarn lint-staged
else
  yarn lint-staged
fi
