name: Lint and Format

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: ESLint (reviewdog)
        id: eslint
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          NODE_ENV=production yarn lint -- --format unix | reviewdog -f=eslint -name=eslint -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true
      - name: Prettier (reviewdog)
        id: prettier
        if: always()
        continue-on-error: true
        uses: reviewdog/action-prettier@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          prettier_command: yarn dlx prettier
          prettier_flags: --check
      - name: Fail if checks failed
        if: steps.eslint.outcome == 'failure' || steps.prettier.outcome == 'failure'
        run: exit 1
